# import os
# from pathlib import Path
# from typing import Dict, Optional
# def build_local_urls(paths: Dict[str,str]) -> Dict[str,Dict[str,str]]:
#     base=os.getenv('BACKEND_BASE_URL','http://localhost:8000').rstrip('/')
#     return {'download':{typ:f'{base}/download/{Path(path).name}' for typ,path in paths.items()},'view':{typ:f'{base}/generated_docs/{Path(path).name}' for typ,path in paths.items()}}
# def build_success_response(paths: Dict[str,str], gcs_paths: Dict[str,str], signed_urls: Dict[str,Optional[str]]) -> Dict[str,object]:
#     urls=build_local_urls(paths)
#     return {'status':'success','output_file':paths.get('pdf'),'word_file':paths.get('docx'),'md_file':paths.get('md'),'html_file':paths.get('html'),'local_download_urls':urls['download'],'local_view_urls':urls['view'],'gcs_pdf':gcs_paths.get('pdf'),'gcs_docx':gcs_paths.get('docx'),'gcs_md':gcs_paths.get('md'),'gcs_html':gcs_paths.get('html'),'signed_urls':signed_urls}
# def build_error_response(error: Exception) -> Dict[str,object]:
#     return {'status':'error','message':str(error),'output_file':None,'word_file':None,'md_file':None,'html_file':None}
# from __future__ import annotations

# import os
# from pathlib import Path
# from typing import Dict, Optional, Any


# def build_local_urls(paths: Dict[str, str]) -> Dict[str, Dict[str, str]]:
#     base = os.getenv(
#         "BACKEND_BASE_URL",
#         "http://localhost:8000",
#     ).rstrip("/")

#     return {
#         "download": {
#             typ: f"{base}/download/{Path(path).name}"
#             for typ, path in paths.items()
#         },
#         "view": {
#             typ: f"{base}/generated_docs/{Path(path).name}"
#             for typ, path in paths.items()
#         },
#     }


# def _is_diagram_asset_key(key: str) -> bool:
#     """
#     Detect diagram asset keys generated by orchestrator.

#     Expected examples:
#       diagram_01_logical_view_01_dot
#       diagram_01_logical_view_01_svg
#       diagram_01_logical_view_01_png
#       diagram_01_logical_view_01_drawio
#     """
#     key = str(key or "").lower()

#     return (
#         key.startswith("diagram_")
#         or key.endswith("_dot")
#         or key.endswith("_svg")
#         or key.endswith("_png")
#         or key.endswith("_drawio")
#     )


# def _group_diagram_assets(
#     paths: Dict[str, str],
#     local_download_urls: Dict[str, str],
#     local_view_urls: Dict[str, str],
#     gcs_paths: Dict[str, str],
#     signed_urls: Dict[str, Optional[str]],
# ) -> Dict[str, Dict[str, Any]]:
#     """
#     Group generated editable diagram assets into a cleaner response structure.

#     Output shape:
#       {
#         "<asset_key>": {
#           "file": "...",
#           "local_download_url": "...",
#           "local_view_url": "...",
#           "gcs_path": "...",
#           "signed_url": "..."
#         }
#       }
#     """
#     diagram_assets: Dict[str, Dict[str, Any]] = {}

#     for key, path in paths.items():
#         if not _is_diagram_asset_key(key):
#             continue

#         diagram_assets[key] = {
#             "file": path,
#             "file_name": Path(path).name if path else "",
#             "local_download_url": local_download_urls.get(key),
#             "local_view_url": local_view_urls.get(key),
#             "gcs_path": gcs_paths.get(key),
#             "signed_url": signed_urls.get(key),
#         }

#     return diagram_assets


# def build_success_response(
#     paths: Dict[str, str],
#     gcs_paths: Dict[str, str],
#     signed_urls: Dict[str, Optional[str]],
# ) -> Dict[str, object]:
#     urls = build_local_urls(paths)

#     local_download_urls = urls["download"]
#     local_view_urls = urls["view"]

#     diagram_assets = _group_diagram_assets(
#         paths=paths,
#         local_download_urls=local_download_urls,
#         local_view_urls=local_view_urls,
#         gcs_paths=gcs_paths,
#         signed_urls=signed_urls,
#     )

#     return {
#         "status": "success",

#         # Backward-compatible top-level document outputs
#         "output_file": paths.get("pdf"),
#         "word_file": paths.get("docx"),
#         "md_file": paths.get("md"),
#         "html_file": paths.get("html"),

#         # Backward-compatible local URL maps
#         "local_download_urls": local_download_urls,
#         "local_view_urls": local_view_urls,

#         # Backward-compatible GCS document outputs
#         "gcs_pdf": gcs_paths.get("pdf"),
#         "gcs_docx": gcs_paths.get("docx"),
#         "gcs_md": gcs_paths.get("md"),
#         "gcs_html": gcs_paths.get("html"),

#         # All signed URLs, including diagram assets
#         "signed_urls": signed_urls,

#         # New clean grouped editable diagram outputs
#         "diagram_assets": diagram_assets,
#     }


# def build_error_response(error: Exception) -> Dict[str, object]:
#     return {
#         "status": "error",
#         "message": str(error),
#         "output_file": None,
#         "word_file": None,
#         "md_file": None,
#         "html_file": None,
#         "diagram_assets": {},
#     }

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict, Optional


# =============================================================================
# Constants / supported dynamic artefacts
# =============================================================================
DOCUMENT_OUTPUT_KEYS = {
    "pdf",
    "docx",
    "md",
    "html",
}

DIAGRAM_ASSET_KEY_PREFIX = "diagram_"

DIAGRAM_ASSET_SUFFIXES = {
    "_dot",
    "_svg",
    "_png",
    "_drawio",
    "_vsdx",
}


# =============================================================================
# URL helpers
# =============================================================================
def _backend_base_url() -> str:
    """
    Resolve backend base URL.

    Default remains localhost for local development.
    """
    return os.getenv(
        "BACKEND_BASE_URL",
        "http://localhost:8000",
    ).rstrip("/")


def _safe_file_name(path: Optional[str]) -> str:
    if not path:
        return ""
    return Path(path).name


def _generated_docs_relative_path(path: Optional[str]) -> str:
    """
    Return a relative path under generated_docs where possible.

    Examples:
        generated_docs/hld.docx
            -> hld.docx

        generated_docs/my_hld_diagram_assets/logical_view_01.drawio
            -> my_hld_diagram_assets/logical_view_01.drawio

    This keeps diagram assets in subfolders addressable via:
        /generated_docs/<relative_path>
    """
    if not path:
        return ""

    p = Path(path)

    try:
        parts = p.parts
        if "generated_docs" in parts:
            idx = parts.index("generated_docs")
            return Path(*parts[idx + 1 :]).as_posix()
    except Exception:
        pass

    return p.name


def _build_download_url(base: str, path: Optional[str]) -> str:
    """
    Build local download URL.

    Backward-compatible behavior:
      /download/<filename>

    If your FastAPI download route supports nested paths, you can switch this
    to use _generated_docs_relative_path(path). For now, filename-only is kept
    to avoid breaking existing /download/{filename} routes.
    """
    file_name = _safe_file_name(path)
    return f"{base}/download/{file_name}" if file_name else ""


def _build_view_url(base: str, path: Optional[str]) -> str:
    """
    Build local view URL.

    For diagram assets in subdirectories, preserve the generated_docs-relative
    path so browser links point to the correct asset location.
    """
    relative_path = _generated_docs_relative_path(path)
    return f"{base}/generated_docs/{relative_path}" if relative_path else ""


def build_local_urls(paths: Dict[str, str]) -> Dict[str, Dict[str, str]]:
    """
    Build local download/view URL maps for all generated artefacts.

    This remains generic and supports:
      - document outputs: pdf/docx/md/html
      - diagram outputs: diagram_*_dot/svg/png/drawio/vsdx
      - any future key with a valid path
    """
    base = _backend_base_url()

    return {
        "download": {
            typ: _build_download_url(base, path)
            for typ, path in paths.items()
        },
        "view": {
            typ: _build_view_url(base, path)
            for typ, path in paths.items()
        },
    }


# =============================================================================
# Artefact classification helpers
# =============================================================================
def _is_document_output_key(key: str) -> bool:
    return str(key or "").lower() in DOCUMENT_OUTPUT_KEYS


def _is_diagram_asset_key(key: str) -> bool:
    """
    Detect diagram asset keys generated by orchestrator.

    Expected examples:
      diagram_logical_view_01_dot
      diagram_logical_view_01_svg
      diagram_logical_view_01_png
      diagram_logical_view_01_drawio
      diagram_logical_view_01_vsdx

    Detection remains generic:
      - any key starting with "diagram_"
      - or any key ending with known diagram suffixes
    """
    normalized_key = str(key or "").lower()

    return (
        normalized_key.startswith(DIAGRAM_ASSET_KEY_PREFIX)
        or any(normalized_key.endswith(suffix) for suffix in DIAGRAM_ASSET_SUFFIXES)
    )


def _asset_type_from_key_or_path(key: str, path: Optional[str]) -> str:
    """
    Resolve asset type for grouped diagram assets.

    Uses file suffix first, then key suffix fallback.
    """
    if path:
        suffix = Path(path).suffix.lower().lstrip(".")
        if suffix:
            return suffix

    normalized_key = str(key or "").lower()

    for suffix in DIAGRAM_ASSET_SUFFIXES:
        if normalized_key.endswith(suffix):
            return suffix.lstrip("_")

    return "asset"


# =============================================================================
# Response grouping helpers
# =============================================================================
def _build_asset_entry(
    key: str,
    path: Optional[str],
    local_download_urls: Dict[str, str],
    local_view_urls: Dict[str, str],
    gcs_paths: Dict[str, str],
    signed_urls: Dict[str, Optional[str]],
) -> Dict[str, Any]:
    """
    Build a consistent response entry for one artefact.
    """
    return {
        "key": key,
        "type": _asset_type_from_key_or_path(key, path),
        "file": path,
        "file_name": _safe_file_name(path),
        "local_download_url": local_download_urls.get(key),
        "local_view_url": local_view_urls.get(key),
        "gcs_path": gcs_paths.get(key),
        "signed_url": signed_urls.get(key),
    }


def _group_diagram_assets(
    paths: Dict[str, str],
    local_download_urls: Dict[str, str],
    local_view_urls: Dict[str, str],
    gcs_paths: Dict[str, str],
    signed_urls: Dict[str, Optional[str]],
) -> Dict[str, Dict[str, Any]]:
    """
    Group generated editable diagram assets into a cleaner response structure.

    Output shape:
      {
        "<asset_key>": {
          "key": "...",
          "type": "drawio|vsdx|svg|png|dot",
          "file": "...",
          "file_name": "...",
          "local_download_url": "...",
          "local_view_url": "...",
          "gcs_path": "...",
          "signed_url": "..."
        }
      }
    """
    diagram_assets: Dict[str, Dict[str, Any]] = {}

    for key, path in paths.items():
        if not _is_diagram_asset_key(key):
            continue

        diagram_assets[key] = _build_asset_entry(
            key=key,
            path=path,
            local_download_urls=local_download_urls,
            local_view_urls=local_view_urls,
            gcs_paths=gcs_paths,
            signed_urls=signed_urls,
        )

    return diagram_assets


def _document_outputs(
    paths: Dict[str, str],
    local_download_urls: Dict[str, str],
    local_view_urls: Dict[str, str],
    gcs_paths: Dict[str, str],
    signed_urls: Dict[str, Optional[str]],
) -> Dict[str, Dict[str, Any]]:
    """
    Group standard document outputs.

    This is additive and does not remove old top-level fields. It provides a
    cleaner structured response for clients that prefer generic handling.
    """
    documents: Dict[str, Dict[str, Any]] = {}

    for key, path in paths.items():
        if not _is_document_output_key(key):
            continue

        documents[key] = _build_asset_entry(
            key=key,
            path=path,
            local_download_urls=local_download_urls,
            local_view_urls=local_view_urls,
            gcs_paths=gcs_paths,
            signed_urls=signed_urls,
        )

    return documents


# =============================================================================
# Public response builders
# =============================================================================
def build_success_response(
    paths: Dict[str, str],
    gcs_paths: Dict[str, str],
    signed_urls: Dict[str, Optional[str]],
) -> Dict[str, object]:
    """
    Build successful render response.

    Backward-compatible fields are preserved:
      - output_file
      - word_file
      - md_file
      - html_file
      - gcs_pdf / gcs_docx / gcs_md / gcs_html
      - signed_urls
      - local_download_urls
      - local_view_urls

    New structured fields:
      - documents
      - diagram_assets
    """
    urls = build_local_urls(paths)

    local_download_urls = urls["download"]
    local_view_urls = urls["view"]

    diagram_assets = _group_diagram_assets(
        paths=paths,
        local_download_urls=local_download_urls,
        local_view_urls=local_view_urls,
        gcs_paths=gcs_paths,
        signed_urls=signed_urls,
    )

    documents = _document_outputs(
        paths=paths,
        local_download_urls=local_download_urls,
        local_view_urls=local_view_urls,
        gcs_paths=gcs_paths,
        signed_urls=signed_urls,
    )

    return {
        "status": "success",

        # ------------------------------------------------------------------
        # Backward-compatible top-level document outputs
        # ------------------------------------------------------------------
        "output_file": paths.get("pdf"),
        "word_file": paths.get("docx"),
        "md_file": paths.get("md"),
        "html_file": paths.get("html"),

        # ------------------------------------------------------------------
        # Backward-compatible local URL maps
        # ------------------------------------------------------------------
        "local_download_urls": local_download_urls,
        "local_view_urls": local_view_urls,

        # ------------------------------------------------------------------
        # Backward-compatible GCS document outputs
        # ------------------------------------------------------------------
        "gcs_pdf": gcs_paths.get("pdf"),
        "gcs_docx": gcs_paths.get("docx"),
        "gcs_md": gcs_paths.get("md"),
        "gcs_html": gcs_paths.get("html"),

        # ------------------------------------------------------------------
        # All signed URLs, including diagram assets
        # ------------------------------------------------------------------
        "signed_urls": signed_urls,

        # ------------------------------------------------------------------
        # New cleaner grouped outputs
        # ------------------------------------------------------------------
        "documents": documents,
        "diagram_assets": diagram_assets,
    }


def build_error_response(error: Exception) -> Dict[str, object]:
    """
    Build failed render response.

    Keep backward-compatible keys so existing UI/client code does not break.
    """
    return {
        "status": "error",
        "message": str(error),

        # Backward-compatible output fields
        "output_file": None,
        "word_file": None,
        "md_file": None,
        "html_file": None,

        # Backward-compatible URL fields
        "local_download_urls": {},
        "local_view_urls": {},
        "signed_urls": {},

        # New structured fields
        "documents": {},
        "diagram_assets": {},
    }