# PROJECT_ID: vf-grp-aib-dev-hk09-sbx-alpha
# REGION: global
# LLM_MODEL: gemini-2.5-pro
# BQ_DATASET_ID: staging
# BQ_TABLE_ID: shoe_items
# GCS_BUCKET_NAME: vf-grp-aib-dev-hk09-sbx-alpha-t25

PROJECT_ID: <project-name>
REGION: global
LLM_MODEL: gemini-2.5-flash
BQ_DATASET_ID: staging
BQ_TABLE_ID: shoe_items
GCS_BUCKET_NAME: <bucket-name>

# IMPORTANT: Setting this flag to 1 will disable web driver
DISABLE_WEB_DRIVER: 1
RUN_AGENT_WITH_DEBUG: False
SERVE_WEB_INTERFACE: True
SESSION_DB_URL: "sqlite:///./sessions.db"

#Proxy Model Variables
# LLM_PROXY_ENDPOINT: https://proxy-service-885279334155.europe-west2.run.app